drop table if exists beer
drop table if exists brewery
drop table if exists hibernate_sequence
drop table if exists beer
drop table if exists brewery
drop table if exists hibernate_sequence
drop table if exists beer
drop table if exists brewery
drop table if exists hibernate_sequence
drop table if exists beer
drop table if exists brewery
drop table if exists hibernate_sequence
